- name: update pkg repo on ubuntu servers w/o sudo
  apt:
    update_cache: yes
  become: true
  become_method: su
  become_user: root

- name: upgrade packages on ubuntu servers w/o sudo
  apt:
    upgrade: dist
    dpkg_options: 'force-confold,force-confdef'
  environment:
    DEBIAN_FRONTEND: noninteractive
  become: true
  become_method: su
  become_user: root
