- name: collectd, cloudwatch, and post-setup AIO for admin server
  hosts: admin
  vars:
    my_hosts: admin
  tasks:
    - name: install cloudwatch-agent and configure
      import_tasks: tasks/install_amzn_cloudwatch_agent_config_ubuntu_generic.yaml
