- name: config cloudwatch for certmanager server
  hosts: certmanager
  vars:
    my_hosts: certmanager
  tasks:
    - name: install cloudwatch-agent and configure
      import_tasks: tasks/install_amzn_cloudwatch_agent_config_ubuntu_generic.yaml
