- name: collectd, cloudwatch, and post-setup AIO for cmt server
  hosts: cmt
  vars:
    my_hosts: cmt
  tasks:
    - name: install cloudwatch-agent and configure
      import_tasks: tasks/install_amzn_cloudwatch_agent_config_ubuntu_generic.yaml
