- name: config cloudwatch for cosmos-lcd server
  hosts: cosmos-lcd
  vars:
    my_hosts: cosmos-lcd
  tasks:
    - name: install cloudwatch-agent and configure
      import_tasks: tasks/install_amzn_cloudwatch_agent_config_ubuntu_generic.yaml
