- name: collectd, cloudwatch, and post-setup AIO for cruiser server
  hosts: cruiser
  vars:
    my_hosts: cruiser
  tasks:
    - name: install cloudwatch-agent and configure
      import_tasks: tasks/install_amzn_cloudwatch_agent_config_ubuntu_generic.yaml
