- name: collectd, cloudwatch, and post-setup AIO for deconomy server
  hosts: deconomy
  vars:
    my_hosts: deconomy
  tasks:
    - name: install cloudwatch-agent and configure
      import_tasks: tasks/install_amzn_cloudwatch_agent_config_ubuntu_generic.yaml
