- name: collectd, cloudwatch, and post-setup AIO for etc server
  hosts: etc
  vars:
    my_hosts: etc
  tasks:
    - name: install cloudwatch-agent and configure
      import_tasks: tasks/install_amzn_cloudwatch_agent_config_ubuntu_generic.yaml
