- name: config cloudwatch for front-2 server
  hosts: front-2
  vars:
    my_hosts: front-2
  tasks:
    - name: install cloudwatch-agent and configure
      import_tasks: tasks/install_amzn_cloudwatch_agent_config_ubuntu_generic.yaml
