- name: collectd, cloudwatch, and post-setup AIO for geth2 server
  hosts: geth2
  vars:
    my_hosts: geth2
  tasks:
    - name: install cloudwatch-agent and configure
      import_tasks: tasks/install_amzn_cloudwatch_agent_config_ubuntu_generic.yaml
