- name: collectd, cloudwatch, and post-setup AIO for geth1 server
  hosts: geth1
  vars:
    my_hosts: geth1
  tasks:
    - name: install cloudwatch-agent and configure
      import_tasks: tasks/install_amzn_cloudwatch_agent_config_ubuntu_generic.yaml
