- name: collectd, cloudwatch, and post-setup AIO for hashtower server
  hosts: hashtower
  vars:
    my_hosts: hashtower
  tasks:
    - name: install cloudwatch-agent and configure
      import_tasks: tasks/install_amzn_cloudwatch_agent_config_ubuntu_generic.yaml
