- name: collectd, cloudwatch, and post-setup AIO for hdac server
  hosts: hdac
  vars:
    my_hosts: hdac
  tasks:
    - name: install cloudwatch-agent and configure
      import_tasks: tasks/install_amzn_cloudwatch_agent_config_ubuntu_generic.yaml
