- name: collectd, cloudwatch, and post-setup AIO for irisnet-full server
  hosts: irisnet-full
  vars:
    my_hosts: irisnet-full
  tasks:
    - name: install cloudwatch-agent and configure
      import_tasks: tasks/install_amzn_cloudwatch_agent_config_ubuntu_generic.yaml
