- name: collectd, cloudwatch, and post-setup AIO for irisnet-lcd server
  hosts: irisnet-lcd
  vars:
    my_hosts: irisnet-lcd
  tasks:
    - name: install cloudwatch-agent and configure
      import_tasks: tasks/install_amzn_cloudwatch_agent_config_ubuntu_generic.yaml
