- name: collectd, cloudwatch, and post-setup AIO for maintenance server
  hosts: maintenance
  vars:
    my_hosts: maintenance
  tasks:
    - name: install cloudwatch-agent and configure
      import_tasks: tasks/install_amzn_cloudwatch_agent_config_ubuntu_generic.yaml
