- name: collectd, cloudwatch, and post-setup AIO for match server
  hosts: match
  vars:
    my_hosts: match
  tasks:
    - name: install cloudwatch-agent and configure
      import_tasks: tasks/install_amzn_cloudwatch_agent_config_ubuntu_generic.yaml
