- name: collectd, cloudwatch, and post-setup AIO for peer-mysql server
  hosts: peer-mysql
  vars:
    my_hosts: peer-mysql
  tasks:
    - name: install cloudwatch-agent and configure
      import_tasks: tasks/install_amzn_cloudwatch_agent_config_ubuntu_generic.yaml
