- name: config cloudwatch for service-admin server
  hosts: service-admin
  vars:
    my_hosts: service-admin
  tasks:
    - name: install cloudwatch-agent and configure
      import_tasks: tasks/install_amzn_cloudwatch_agent_config_ubuntu_generic.yaml
