- name: collectd, cloudwatch, and post-setup AIO for terra-full server
  hosts: terra-full
  vars:
    my_hosts: terra-full
  tasks:
    - name: install cloudwatch-agent and configure
      import_tasks: tasks/install_amzn_cloudwatch_agent_config_ubuntu_generic.yaml
