- name: config cloudwatch for wg-bip server
  hosts: wg-bip
  vars:
    my_hosts: wg-bip
  tasks:
    - name: install cloudwatch-agent and configure
      import_tasks: tasks/install_amzn_cloudwatch_agent_config_ubuntu_generic.yaml
